### ISSUE TITLE
__reload removed

### ISSUE THREAD

**Issue by happylinks** [capaj/systemjs-hot-reloader#30]
I see that this commit:
https://github.com/capaj/systemjs-hot-reloader/commit/5f77835ff27cfc836bada2bfe999876b76ff43fb
removed this one:
https://github.com/capaj/systemjs-hot-reloader/commit/aac2b5e7e3eadc7345a7fb0654a9bf4e3f9bcb2c

Was this an accident? The __reload is still in the docs.

**Comment by capaj** [comment]
@happylinks thanks for pointing that out. That is why I need to write those unit tests already!

thanks, will fix in 0.5.1

**Comment by capaj** [comment]
fixed in 85254f3ab0080d1d3cf14031950ae79a55ae0075

**Comment by peteruithoven** [comment]
I'm afraid this isn't completely fixed. With the recent changes the reloader only reloads the root module, instead of all the individual modules. See: https://github.com/capaj/systemjs-hot-reloader/issues/18#issuecomment-163950281 This means it can't call the __reload of the individual modules. The __reload can currently only be used on the root module(s).

**Comment by capaj** [comment]
@peteruithoven that was wrong from the start I am afraid: https://github.com/capaj/systemjs-hot-reloader/blob/1d64dfb26e0bacc7f84c20a231762ea26b35b2b6/jspm-hot-reloader.js#L184

will need to look at better fix
